FROM python:3.8

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    libfreetype6-dev \
    libmupdf-dev \
    libjbig2dec0-dev \
    libjpeg-dev \
    libopenjp2-7-dev \
    libharfbuzz-dev \
    libxml2-dev \
    libxslt-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app

COPY requirements*.txt /app/

RUN pip3 install --no-cache-dir -r requirements*.txt

COPY . /app/

EXPOSE 5000

CMD ["python3", "app.py"]
