# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from app.models.base_model_ import Model
from app import util


class CustomerIdDocsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, document_id: str=None, content: str=None, metadata: object=None):  # noqa: E501
        """CustomerIdDocsBody - a model defined in Swagger

        :param document_id: The document_id of this CustomerIdDocsBody.  # noqa: E501
        :type document_id: str
        :param content: The content of this CustomerIdDocsBody.  # noqa: E501
        :type content: str
        :param metadata: The metadata of this CustomerIdDocsBody.  # noqa: E501
        :type metadata: object
        """
        self.swagger_types = {
            'document_id': str,
            'content': str,
            'metadata': object
        }

        self.attribute_map = {
            'document_id': 'documentId',
            'content': 'content',
            'metadata': 'metadata'
        }
        self._document_id = document_id
        self._content = content
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'CustomerIdDocsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The customerId_docs_body of this CustomerIdDocsBody.  # noqa: E501
        :rtype: CustomerIdDocsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def document_id(self) -> str:
        """Gets the document_id of this CustomerIdDocsBody.

        The ID of the document.  # noqa: E501

        :return: The document_id of this CustomerIdDocsBody.
        :rtype: str
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id: str):
        """Sets the document_id of this CustomerIdDocsBody.

        The ID of the document.  # noqa: E501

        :param document_id: The document_id of this CustomerIdDocsBody.
        :type document_id: str
        """

        self._document_id = document_id

    @property
    def content(self) -> str:
        """Gets the content of this CustomerIdDocsBody.

        The content of the document.  # noqa: E501

        :return: The content of this CustomerIdDocsBody.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this CustomerIdDocsBody.

        The content of the document.  # noqa: E501

        :param content: The content of this CustomerIdDocsBody.
        :type content: str
        """

        self._content = content

    @property
    def metadata(self) -> object:
        """Gets the metadata of this CustomerIdDocsBody.

        Metadata associated with the document.  # noqa: E501

        :return: The metadata of this CustomerIdDocsBody.
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: object):
        """Sets the metadata of this CustomerIdDocsBody.

        Metadata associated with the document.  # noqa: E501

        :param metadata: The metadata of this CustomerIdDocsBody.
        :type metadata: object
        """

        self._metadata = metadata
