# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from app.models.base_model_ import Model
from app import util


class CustomerIdDocIdBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, content: str=None, metadata: object=None):  # noqa: E501
        """CustomerIdDocIdBody - a model defined in Swagger

        :param content: The content of this CustomerIdDocIdBody.  # noqa: E501
        :type content: str
        :param metadata: The metadata of this CustomerIdDocIdBody.  # noqa: E501
        :type metadata: object
        """
        self.swagger_types = {
            'content': str,
            'metadata': object
        }

        self.attribute_map = {
            'content': 'content',
            'metadata': 'metadata'
        }
        self._content = content
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'CustomerIdDocIdBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The customerId_docId_body of this CustomerIdDocIdBody.  # noqa: E501
        :rtype: CustomerIdDocIdBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def content(self) -> str:
        """Gets the content of this CustomerIdDocIdBody.

        The content of the document.  # noqa: E501

        :return: The content of this CustomerIdDocIdBody.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this CustomerIdDocIdBody.

        The content of the document.  # noqa: E501

        :param content: The content of this CustomerIdDocIdBody.
        :type content: str
        """

        self._content = content

    @property
    def metadata(self) -> object:
        """Gets the metadata of this CustomerIdDocIdBody.

        Metadata associated with the document.  # noqa: E501

        :return: The metadata of this CustomerIdDocIdBody.
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: object):
        """Sets the metadata of this CustomerIdDocIdBody.

        Metadata associated with the document.  # noqa: E501

        :param metadata: The metadata of this CustomerIdDocIdBody.
        :type metadata: object
        """

        self._metadata = metadata
