FROM python:3.12


# RUN apk add --no-cache \
#     gcc \
#     musl-dev \
#     libffi-dev \
#     openssl-dev

RUN mkdir /app
WORKDIR /app

# COPY ./ /app/

COPY requirements*.txt /app/
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt



COPY ./ /app/


EXPOSE 8000


CMD ["python3", "-m", "app"]
