FROM alpine:3.19

ENV PYTHONUNBUFFERED=1
 
RUN echo "**** install Python ****" && \
    apk add --no-cache python3 && \
    if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi && \
    \
    echo "**** install pip ****" && \
    rm /usr/lib/python3.11/EXTERNALLY-MANAGED && \
    python -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    pip install --no-cache --upgrade pip setuptools wheel

RUN mkdir /legelshield
WORKDIR /legelshield

# COPY ./ /app/

COPY requirements.txt /legelshield/
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt



COPY ./ /legelshield/


EXPOSE 8080


CMD ["python3", "-m", "app"]
