apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legal
  template:
    metadata:
      labels:
        app: legal
    spec:
      containers:
        - name: legal
          image: 'alphalegal.azurecr.io/legalschield:v10'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: legal

